name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 13
      - run: yarn install --ci
      - run: yarn build
      - run: yarn lint
