name: Netlify

on: push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - run: yarn install --ci

      - uses: nelonoel/branch-name@v1.0.1

      - run: yarn typedoc
      - name: Docsify variables
        env:
          DOMAIN: ${{ env.BRANCH_NAME == 'master' && 'forms.hypermedia.app' || format('{0}--shaperone.netlify.app', env.BRANCH_NAME) }}
        run: npx json -I -f dist/variables.json -e "this.playground='https://$DOMAIN/playground'"

      - name: Publish preview
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: Preview ${{ env.BRANCH_NAME }}
          build_directory: dist
          deploy_alias: ${{ env.BRANCH_NAME }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.BRANCH_NAME == 'master' }}

      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify Site
          state: success
          target_url: https://${{ env.BRANCH_NAME }}--shaperone.netlify.app
